CREATE TABLE `store` (
     `id` varchar(255) NOT NULL,
     `address_code` int(11) DEFAULT NULL COMMENT '시군구코드',
     `address_name` varchar(255) DEFAULT NULL COMMENT '시군구명',
     `administrative_dong_code` int(11) DEFAULT NULL COMMENT '행정동코드',
     `administrative_dong_name` varchar(255) DEFAULT NULL COMMENT '행정동명',
     `branch_name` varchar(255) DEFAULT NULL COMMENT '지점명',
     `build_main_number` int(11) DEFAULT NULL COMMENT '건물본번지',
     `build_mame` varchar(255) DEFAULT NULL COMMENT '건물명',
     `build_mgmt_number` varchar(255) DEFAULT NULL COMMENT '건물관리번호',
     `build_sub_number` int(11) DEFAULT NULL COMMENT '건물부번지',
     `business_large_code` varchar(255) DEFAULT NULL COMMENT '상권업종대분류코드',
     `business_large_name` varchar(255) DEFAULT NULL COMMENT '상권업종대분류명',
     `business_middle_code` varchar(255) DEFAULT NULL COMMENT '상권업종중분류코드',
     `business_middle_name` varchar(255) DEFAULT NULL COMMENT '상권업종중분류명',
     `business_small_code` varchar(255) DEFAULT NULL COMMENT '상권업종소분류코드',
     `business_small_name` varchar(255) DEFAULT NULL COMMENT '상권업종소분류명',
     `city_code` int(11) DEFAULT NULL COMMENT '시도코드',
     `city_name` varchar(255) DEFAULT NULL COMMENT '시도명',
     `dong` varchar(255) DEFAULT NULL COMMENT '동정보',
     `floor` varchar(255) DEFAULT NULL COMMENT '층정보',
     `ho` varchar(255) DEFAULT NULL COMMENT '호정보',
     `land_code` int(11) DEFAULT NULL COMMENT '대지구분코드',
     `land_name` varchar(255) DEFAULT NULL COMMENT '대지구분명',
     `latitude` double DEFAULT NULL COMMENT '위도',
     `legal_operation_code` varchar(255) DEFAULT NULL COMMENT '법정동코드',
     `legal_operation_name` varchar(255) DEFAULT NULL COMMENT '법정동명',
     `local_address` varchar(255) DEFAULT NULL COMMENT '지번주소',
     `local_main_number` int(11) DEFAULT NULL COMMENT '지번본번지',
     `local_sub_number` int(11) DEFAULT NULL COMMENT '지번부번지',
     `longitude` double DEFAULT NULL COMMENT '경도',
     `new_postal_code` int(11) DEFAULT NULL COMMENT '신우편번호',
     `number_code` varchar(255) DEFAULT NULL COMMENT '지번코드',
     `old_postal_code` int(11) DEFAULT NULL COMMENT '구우편번호',
     `road_name` varchar(255) DEFAULT NULL COMMENT '도로명',
     `road_name_address` varchar(255) DEFAULT NULL COMMENT '도로명주소',
     `road_name_code` varchar(255) DEFAULT NULL COMMENT '도로명코드',
     `standard_code` varchar(255) DEFAULT NULL COMMENT '표준산업분류코드',
     `standard_name` varchar(255) DEFAULT NULL COMMENT '표준산업분류명',
     `trade_name` varchar(255) DEFAULT NULL COMMENT '상호명',
     PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_uca1400_ai_ci;